<?php
session_start();
require("../config.php");
$case = $_REQUEST['service'];

switch($case)
{
    case 'symptomselect':
    {

        $user_name = $_POST['username'];
//      $user_name="silvi";
        $flag=0;
        $sql1 ="SELECT * FROM symptom WHERE username='$user_name'";


        if($query1 = mysql_query($sql1))
        {
            $flag =1;

            if($flag == '1')
            {

                $json = '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "Yes", "symptomuser List" : [ ';
                for($i=0;$i<mysql_num_rows($query1);$i++)
                {


                    $row		= mysql_fetch_object($query1);


                    $json 		.= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "Yes", "patient_no" : "'.$row->patient_no.'", "username" : "'.$row->username.'", "pname" : "'.$row->pname.'", "number" : "'.$row->number.'", "date" : "'.$row->date.'", "achepath" : "'.$row->achepath.'", "acheleft" : "'.$row->acheleft.'", "achetop" : "'.$row->achetop.'","achepath1" : "'.$row->achepath1.'", "acheleft1" : "'.$row->acheleft1.'", "achetop1" : "'.$row->achetop1.'","achepath2" : "'.$row->achepath2.'", "acheleft2" : "'.$row->acheleft2.'", "achetop2" : "'.$row->achetop2.'","achepath3" : "'.$row->achepath3.'", "acheleft3" : "'.$row->acheleft3.'", "achetop3" : "'.$row->achetop3.'","achepath4" : "'.$row->achepath4.'", "acheleft4" : "'.$row->acheleft4.'", "achetop4" : "'.$row->achetop4.'","achepath5" : "'.$row->achepath5.'", "acheleft5" : "'.$row->acheleft5.'", "achetop5" : "'.$row->achetop5.'","achepath6" : "'.$row->achepath6.'", "acheleft6" : "'.$row->acheleft6.'", "achetop6" : "'.$row->achetop6.'","achepath7" : "'.$row->achepath7.'", "acheleft7" : "'.$row->acheleft7.'", "achetop7" : "'.$row->achetop7.'","achepath8" : "'.$row->achepath8.'", "acheleft8" : "'.$row->acheleft8.'", "achetop8" : "'.$row->achetop8.'","achepath9" : "'.$row->achepath9.'", "acheleft9" : "'.$row->acheleft9.'", "achetop9" : "'.$row->achetop9.'","numbpath" : "'.$row->numbpath.'", "numbleft" : "'.$row->numbleft.'", "numbtop" : "'.$row->numbtop.'","numbpath1" : "'.$row->numbpath1.'", "numbleft1" : "'.$row->numbleft1.'", "numbtop1" : "'.$row->numbtop1.'","numbpath2" : "'.$row->numbpath2.'", "numbleft2" : "'.$row->numbleft2.'", "numbtop2" : "'.$row->numbtop2.'","numbpath3" : "'.$row->numbpath3.'", "numbleft3" : "'.$row->numbleft3.'", "numbtop3" : "'.$row->numbtop3.'","numbpath4" : "'.$row->numbpath4.'", "numbleft4" : "'.$row->numbleft4.'", "numbtop4" : "'.$row->numbtop4.'","numbpath5" : "'.$row->numbpath5.'", "numbleft5" : "'.$row->numbleft5.'", "numbtop5" : "'.$row->numbtop5.'","numbpath6" : "'.$row->numbpath6.'", "numbleft6" : "'.$row->numbleft6.'", "numbtop6" : "'.$row->numbtop6.'","numbpath7" : "'.$row->numbpath7.'", "numbleft7" : "'.$row->numbleft7.'", "numbtop7" : "'.$row->numbtop7.'","numbpath8" : "'.$row->numbpath8.'", "numbleft8" : "'.$row->numbleft8.'", "numbtop8" : "'.$row->numbtop8.'","numbpath9" : "'.$row->numbpath9.'", "numbleft9" : "'.$row->numbleft9.'", "numbtop9" : "'.$row->numbtop9.'","pinpath" : "'.$row->pinpath.'", "pinleft" : "'.$row->pinleft.'", "pintop" : "'.$row->pintop.'","pinpath1" : "'.$row->pinpath1.'", "pinleft1" : "'.$row->pinleft1.'", "pintop1" : "'.$row->pintop1.'","pinpath2" : "'.$row->pinpath2.'", "pinleft2" : "'.$row->pinleft2.'", "pintop2" : "'.$row->pintop2.'","pinpath3" : "'.$row->pinpath3.'", "pinleft3" : "'.$row->pinleft3.'", "pintop3" : "'.$row->pintop3.'","pinpath4" : "'.$row->pinpath4.'", "pinleft4" : "'.$row->pinleft4.'", "pintop4" : "'.$row->pintop4.'","pinpath5" : "'.$row->pinpath5.'", "pinleft5" : "'.$row->pinleft5.'", "pintop5" : "'.$row->pintop5.'","pinpath6" : "'.$row->pinpath6.'", "pinleft6" : "'.$row->pinleft6.'", "pintop6" : "'.$row->pintop6.'","pinpath7" : "'.$row->pinpath7.'", "pinleft7" : "'.$row->pinleft7.'", "pintop7" : "'.$row->pintop7.'","pinpath8" : "'.$row->pinpath8.'", "pinleft8" : "'.$row->pinleft8.'", "pintop8" : "'.$row->pintop8.'","pinpath9" : "'.$row->pinpath9.'", "pinleft9" : "'.$row->pinleft9.'", "pintop9" : "'.$row->pintop9.'","burnpath" : "'.$row->burnpath.'", "burnleft" : "'.$row->burnleft.'", "burntop" : "'.$row->burntop.'","burnpath1" : "'.$row->burnpath1.'", "burnleft1" : "'.$row->burnleft1.'", "burntop1" : "'.$row->burntop1.'","burnpath2" : "'.$row->burnpath2.'", "burnleft2" : "'.$row->burnleft2.'", "burntop2" : "'.$row->burntop2.'","burnpath3" : "'.$row->burnpath3.'", "burnleft3" : "'.$row->burnleft3.'", "burntop3" : "'.$row->burntop3.'","burnpath4" : "'.$row->burnpath4.'", "burnleft4" : "'.$row->burnleft4.'", "burntop4" : "'.$row->burntop4.'","burnpath5" : "'.$row->burnpath5.'", "burnleft5" : "'.$row->burnleft5.'", "burntop5" : "'.$row->burntop5.'","burnpath6" : "'.$row->burnpath6.'", "burnleft6" : "'.$row->burnleft6.'", "burntop6" : "'.$row->burntop6.'","burnpath7" : "'.$row->burnpath7.'", "burnleft7" : "'.$row->burnleft7.'", "burntop7" : "'.$row->burntop7.'","burnpath8" : "'.$row->burnpath8.'", "burnleft8" : "'.$row->burnleft8.'", "burntop8" : "'.$row->burntop8.'","burnpath9" : "'.$row->burnpath9.'", "burnleft9" : "'.$row->burnleft9.'", "burntop9" : "'.$row->burntop9.'","stabpath" : "'.$row->stabpath.'", "stableft" : "'.$row->stableft.'", "stabtop" : "'.$row->stabtop.'","stabpath1" : "'.$row->stabpath1.'", "stableft1" : "'.$row->stableft1.'", "stabtop1" : "'.$row->stabtop1.'","stabpath2" : "'.$row->stabpath2.'", "stableft2" : "'.$row->stableft2.'", "stabtop2" : "'.$row->stabtop2.'","stabpath3" : "'.$row->stabpath3.'", "stableft3" : "'.$row->stableft3.'", "stabtop3" : "'.$row->stabtop3.'","stabpath4" : "'.$row->stabpath4.'", "stableft4" : "'.$row->stableft4.'", "stabtop4" : "'.$row->stabtop4.'","stabpath5" : "'.$row->stabpath5.'", "stableft5" : "'.$row->stableft5.'", "stabtop5" : "'.$row->stabtop5.'","stabpath6" : "'.$row->stabpath6.'", "stableft6" : "'.$row->stableft6.'", "stabtop6" : "'.$row->stabtop6.'","stabpath7" : "'.$row->stabpath7.'", "stableft7" : "'.$row->stableft7.'", "stabtop7" : "'.$row->stabtop7.'","stabpath8" : "'.$row->stabpath8.'", "stableft8" : "'.$row->stableft8.'", "stabtop8" : "'.$row->stabtop8.'","stabpath9" : "'.$row->stabpath9.'", "stableft9" : "'.$row->stableft9.'", "stabtop9" : "'.$row->stabtop9.'", "message" : "1" } }';

                }
                $json = rtrim($json,',');
                $json .= '], "message" : "1" } }';
            }
        }
        if($flag == '0')
        {
            $json 		= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "No", "message" : "'.$error.'" } }';
        }

        echo $json;

        break;
    }
    case 'symptomedit':
    {
        $user_name=$_POST['username'];
        $pname=$_POST['pname'];
        $number=$_POST['number'];
        $date=$_POST['date'];
        $achepath=$_POST['achepath'];
        $acheleft=$_POST['acheleft'];
        $achetop=$_POST['achetop'];
        $achepath1=$_POST['achepath1'];
        $acheleft1=$_POST['acheleft1'];
        $achetop1=$_POST['achetop1'];
        $achepath2=$_POST['achepath2'];
        $acheleft2=$_POST['acheleft2'];
        $achetop2=$_POST['achetop2'];
        $achepath3=$_POST['achepath3'];
        $acheleft3=$_POST['acheleft3'];
        $achetop3=$_POST['achetop3'];
        $achepath4=$_POST['achepath4'];
        $acheleft4=$_POST['acheleft4'];
        $achetop4=$_POST['achetop4'];
        $achepath5=$_POST['achepath5'];
        $acheleft5=$_POST['acheleft5'];
        $achetop5=$_POST['achetop5'];
        $achepath6=$_POST['achepath6'];
        $acheleft6=$_POST['acheleft6'];
        $achetop6=$_POST['achetop6'];
        $achepath7=$_POST['achepath7'];
        $acheleft7=$_POST['acheleft7'];
        $achetop7=$_POST['achetop7'];
        $achepath8=$_POST['achepath8'];
        $acheleft8=$_POST['acheleft8'];
        $achetop8=$_POST['achetop8'];
        $achepath9=$_POST['achepath9'];
        $acheleft9=$_POST['acheleft9'];
        $achetop9=$_POST['achetop9'];
        $numbpath=$_POST['numbpath'];
        $numbleft=$_POST['numbleft'];
        $numbtop=$_POST['numbtop'];
        $numbpath1=$_POST['numbpath1'];
        $numbleft1=$_POST['numbleft1'];
        $numbtop1=$_POST['numbtop1'];
        $numbpath2=$_POST['numbpath2'];
        $numbleft2=$_POST['numbleft2'];
        $numbtop2=$_POST['numbtop2'];
        $numbpath3=$_POST['numbpath3'];
        $numbleft3=$_POST['numbleft3'];
        $numbtop3=$_POST['numbtop3'];
        $numbpath4=$_POST['numbpath4'];
        $numbleft4=$_POST['numbleft4'];
        $numbtop4=$_POST['numbtop4'];
        $numbpath5=$_POST['numbpath5'];
        $numbleft5=$_POST['numbleft5'];
        $numbtop5=$_POST['numbtop5'];
        $numbpath6=$_POST['numbpath6'];
        $numbleft6=$_POST['numbleft6'];
        $numbtop6=$_POST['numbtop6'];
        $numbpath7=$_POST['numbpath7'];
        $numbleft7=$_POST['numbleft7'];
        $numbtop7=$_POST['numbtop7'];
        $numbpath8=$_POST['numbpath8'];
        $numbleft8=$_POST['numbleft8'];
        $numbtop8=$_POST['numbtop8'];
        $numbpath9=$_POST['numbpath9'];
        $numbleft9=$_POST['numbleft9'];
        $numbtop9=$_POST['numbtop9'];
        $pinpath=$_POST['pinpath'];
        $pinleft=$_POST['pinleft'];
        $pintop=$_POST['pintop'];
        $pinpath1=$_POST['pinpath1'];
        $pinleft1=$_POST['pinleft1'];
        $pintop1=$_POST['pintop1'];
        $pinpath2=$_POST['pinpath2'];
        $pinleft2=$_POST['pinleft2'];
        $pintop2=$_POST['pintop2'];
        $pinpath3=$_POST['pinpath3'];
        $pinleft3=$_POST['pinleft3'];
        $pintop3=$_POST['pintop3'];
        $pinpath4=$_POST['pinpath4'];
        $pinleft4=$_POST['pinleft4'];
        $pintop4=$_POST['pintop4'];
        $pinpath5=$_POST['pinpath5'];
        $pinleft5=$_POST['pinleft5'];
        $pintop5=$_POST['pintop5'];
        $pinpath6=$_POST['pinpath6'];
        $pinleft6=$_POST['pinleft6'];
        $pintop6=$_POST['pintop6'];
        $pinpath7=$_POST['pinpath7'];
        $pinleft7=$_POST['pinleft7'];
        $pintop7=$_POST['pintop7'];
        $pinpath8=$_POST['pinpath8'];
        $pinleft8=$_POST['pinleft8'];
        $pintop8=$_POST['pintop8'];
        $pinpath9=$_POST['pinpath9'];
        $pinleft9=$_POST['pinleft9'];
        $pintop9=$_POST['pintop9'];
        $burnpath=$_POST['burnpath'];
        $burnleft=$_POST['burnleft'];
        $burntop=$_POST['burntop'];
        $burnpath1=$_POST['burnpath1'];
        $burnleft1=$_POST['burnleft1'];
        $burntop1=$_POST['burntop1'];
        $burnpath2=$_POST['burnpath2'];
        $burnleft2=$_POST['burnleft2'];
        $burntop2=$_POST['burntop2'];
        $burnpath3=$_POST['burnpath3'];
        $burnleft3=$_POST['burnleft3'];
        $burntop3=$_POST['burntop3'];
        $burnpath4=$_POST['burnpath4'];
        $burnleft4=$_POST['burnleft4'];
        $burntop4=$_POST['burntop4'];
        $burnpath5=$_POST['burnpath5'];
        $burnleft5=$_POST['burnleft5'];
        $burntop5=$_POST['burntop5'];
        $burnpath6=$_POST['burnpath6'];
        $burnleft6=$_POST['burnleft6'];
        $burntop6=$_POST['burntop6'];
        $burnpath7=$_POST['burnpath7'];
        $burnleft7=$_POST['burnleft7'];
        $burntop7=$_POST['burntop7'];
        $burnpath8=$_POST['burnpath8'];
        $burnleft8=$_POST['burnleft8'];
        $burntop8=$_POST['burntop8'];
        $burnpath9=$_POST['burnpath9'];
        $burnleft9=$_POST['burnleft9'];
        $burntop9=$_POST['burntop9'];
        $stabpath=$_POST['stabpath'];
        $stableft=$_POST['stableft'];
        $stabtop=$_POST['stabtop'];
        $stabpath1=$_POST['stabpath1'];
        $stableft1=$_POST['stableft1'];
        $stabtop1=$_POST['stabtop1'];
        $stabpath2=$_POST['stabpath2'];
        $stableft2=$_POST['stableft2'];
        $stabtop2=$_POST['stabtop2'];
        $stabpath3=$_POST['stabpath3'];
        $stableft3=$_POST['stableft3'];
        $stabtop3=$_POST['stabtop3'];
        $stabpath4=$_POST['stabpath4'];
        $stableft4=$_POST['stableft4'];
        $stabtop4=$_POST['stabtop4'];
        $stabpath5=$_POST['stabpath5'];
        $stableft5=$_POST['stableft5'];
        $stabtop5=$_POST['stabtop5'];
        $stabpath6=$_POST['stabpath6'];
        $stableft6=$_POST['stableft6'];
        $stabtop6=$_POST['stabtop6'];
        $stabpath7=$_POST['stabpath7'];
        $stableft7=$_POST['stableft7'];
        $stabtop7=$_POST['stabtop7'];
        $stabpath8=$_POST['stabpath8'];
        $stableft8=$_POST['stableft8'];
        $stabtop8=$_POST['stabtop8'];
        $stabpath9=$_POST['stabpath9'];
        $stableft9=$_POST['stableft9'];
        $stabtop9=$_POST['stabtop9'];


//        $achepath="";
//        $acheleft="";
//        $achetop="";
//        $achepath1="";
//        $acheleft1="";
//        $achetop1="";
//        $achepath2="";
//        $acheleft2="";
//        $achetop2="";
//        $achepath3="";
//        $acheleft3="";
//        $achetop3="";
//        $achepath4="";
//        $acheleft4="";
//        $achetop4="";
//        $achepath5="";
//        $acheleft5="";
//        $achetop5="";
//        $achepath6="";
//        $acheleft6="";
//        $achetop6="";
//        $achepath7="";
//        $acheleft7="";
//        $achetop7="";
//        $achepath8="";
//        $acheleft8="";
//        $achetop8="";
//        $achepath9="";
//        $acheleft9="";
//        $achetop9="";
//        $numbpath="";
//        $numbleft="";
//        $numbtop="";
//        $numbpath1="";
//        $numbleft1="";
//        $numbtop1="";
//        $numbpath2="";
//        $numbleft2="";
//        $numbtop2="";
//        $numbpath3="";
//        $numbleft3="";
//        $numbtop3="";
//        $numbpath4="";
//        $numbleft4="";
//        $numbtop4="";
//        $numbpath5="";
//        $numbleft5="";
//        $numbtop5="";
//        $numbpath6="";
//        $numbleft6="";
//        $numbtop6="";
//        $numbpath7="";
//        $numbleft7="";
//        $numbtop7="";
//        $numbpath8="";
//        $numbleft8="";
//        $numbtop8="";
//        $numbpath9="";
//        $numbleft9="";
//        $numbtop9="";
//        $pinpath="";
//        $pinleft="";
//        $pintop="";
//        $pinpath1="";
//        $pinleft1="";
//        $pintop1="";
//        $pinpath2="";
//        $pinleft2="";
//        $pintop2="";
//        $pinpath3="";
//        $pinleft3="";
//        $pintop3="";
//        $pinpath4="";
//        $pinleft4="";
//        $pintop4="";
//        $pinpath5="";
//        $pinleft5="";
//        $pintop5="";
//        $pinpath6="";
//        $pinleft6="";
//        $pintop6="";
//        $pinpath7="";
//        $pinleft7="";
//        $pintop7="";
//        $pinpath8="";
//        $pinleft8="";
//        $pintop8="";
//        $pinpath9="";
//        $pinleft9="";
//        $pintop9="";
//        $burnpath="";
//        $burnleft="";
//        $burntop="";
//        $burnpath1="";
//        $burnleft1="";
//        $burntop1="";
//        $burnpath2="";
//        $burnleft2="";
//        $burntop2="";
//        $burnpath3="";
//        $burnleft3="";
//        $burntop3="";
//        $burnpath4="";
//        $burnleft4="";
//        $burntop4="";
//        $burnpath5="";
//        $burnleft5="";
//        $burntop5="";
//        $burnpath6="";
//        $burnleft6="";
//        $burntop6="";
//        $burnpath7="";
//        $burnleft7="";
//        $burntop7="";
//        $burnpath8="";
//        $burnleft8="";
//        $burntop8="";
//        $burnpath9="";
//        $burnleft9="";
//        $burntop9="";
//        $stabpath="";
//        $stableft="";
//        $stabtop="";
//        $stabpath1="";
//        $stableft1="";
//        $stabtop1="";
//        $stabpath2="";
//        $stableft2="";
//        $stabtop2="";
//        $stabpath3="";
//        $stableft3="";
//        $stabtop3="";
//        $stabpath4="";
//        $stableft4="";
//        $stabtop4="";
//        $stabpath5="";
//        $stableft5="";
//        $stabtop5="";
//        $stabpath6="";
//        $stableft6="";
//        $stabtop6="";
//        $stabpath7="";
//        $stableft7="";
//        $stabtop7="";
//        $stabpath8="";
//        $stableft8="";
//        $stabtop8="";
//        $stabpath9="";
//        $stableft9="";
//        $stabtop9="";
 /*       $user_name="silvi";
        $pname="silviyarani";
        $number="100";
        $date="10/12/2014";
        $achepath="resources/images/aches.png";
        $acheleft="10";
        $achetop="10";
        $achepath1="resources/images/aches.png";
        $acheleft1="20";
        $achetop1="20";
        $achepath2="resources/images/aches.png";
$acheleft2="30";
$achetop2="30";
$achepath3="resources/images/aches.png";
$acheleft3="40";
$achetop3="40";
$achepath4="resources/images/aches.png";
$acheleft4="50";
$achetop4="50";
$achepath5="resources/images/aches.png";
$acheleft5="60";
$achetop5="60";
$achepath6="resources/images/aches.png";
$acheleft6="70";
$achetop6="70";
$achepath7="resources/images/aches.png";
$acheleft7="80";
$achetop7="80";
$achepath8="resources/images/aches.png";
$acheleft8="90";
$achetop8="90";
$achepath9="resources/images/aches.png";
$acheleft9="100";
$achetop9="100";
$numbpath="resources/images/numb.png";
$numbleft="10";
$numbtop="10";
$numbpath1="resources/images/numb.png";
$numbleft1="20";
$numbtop1="20";
$numbpath2="resources/images/numb.png";
$numbleft2="30";
$numbtop2="30";
$numbpath3="resources/images/numb.png";
$numbleft3="40";
$numbtop3="40";
$numbpath4="resources/images/numb.png";
$numbleft4="50";
$numbtop4="50";
$numbpath5="resources/images/numb.png";
$numbleft5="60";
$numbtop5="60";
$numbpath6="resources/images/numb.png";
$numbleft6="70";
$numbtop6="70";
$numbpath7="resources/images/numb.png";
$numbleft7="80";
$numbtop7="80";
$numbpath8="resources/images/numb.png";
$numbleft8="90";
$numbtop8="90";
$numbpath9="resources/images/numb.png";
$numbleft9="100";
$numbtop9="100";
$pinpath="resources/images/pin.png";
$pinleft="15";
$pintop="15";
$pinpath1="resources/images/ pin.png";
$pinleft1="25";
$pintop1="25";
$pinpath2="resources/images/ pin.png";
$pinleft2="35";
$pintop2="35";
$pinpath3="resources/images/ pin.png";
$pinleft3="45";
$pintop3="45";
$pinpath4="resources/images/ pin.png";
$pinleft4="55";
$pintop4="55";
$pinpath5="resources/images/ pin.png";
$pinleft5="65";
$pintop5="65";
$pinpath6="resources/images/ pin.png";
$pinleft6="75";
$pintop6="75";
$pinpath7="resources/images/ pin.png";
$pinleft7="85";
$pintop7="85";
$pinpath8="resources/images/ pin.png";
$pinleft8="95";
$pintop8="95";
$pinpath9="resources/images/ pin.png";
$pinleft9="105";
$pintop9="105";
$burnpath="resources/images/ burn.png";
$burnleft="20";
$burntop="22";
$burnpath1="resources/images/ burn.png";
$burnleft1="30";
$burntop1="32";
$burnpath2="resources/images/ burn.png";
$burnleft2="10";
$burntop2="12";
$burnpath3="resources/images/ burn.png";
$burnleft3="40";
$burntop3="42";
$burnpath4="resources/images/ burn.png";
$burnleft4="50";
$burntop4="52";
$burnpath5="resources/images/ burn.png";
$burnleft5="60";
$burntop5="62";
$burnpath6="resources/images/ burn.png";
$burnleft6="70";
$burntop6="72";
$burnpath7="resources/images/ burn.png";
$burnleft7="80";
$burntop7="82";
$burnpath8="resources/images/ burn.png";
$burnleft8="90";
$burntop8="92";
$burnpath9="resources/images/ burn.png";
$burnleft9="100";
$burntop9="102";
$stabpath="resources/images/stabbing.png";
$stableft="11";
$stabtop="22";
$stabpath1="resources/images/stabbing.png";
$stableft1="22";
$stabtop1="33";
$stabpath2="resources/images/stabbing.png";
$stableft2="33";
$stabtop2="44";
$stabpath3="resources/images/stabbing.png";
$stableft3="44";
$stabtop3="55";
$stabpath4="resources/images/stabbing.png";
$stableft4="55";
$stabtop4="66";
$stabpath5="resources/images/stabbing.png";
$stableft5="66";
$stabtop5="77";
$stabpath6="resources/images/stabbing.png";
$stableft6="77";
$stabtop6="88";
$stabpath7="resources/images/stabbing.png";
$stableft7="88";
$stabtop7="99";
$stabpath8="resources/images/stabbing.png";
$stableft8="99";
$stabtop8="111";
$stabpath9="resources/images/stabbing.png";
$stableft9="111";
$stabtop9="112";

*/

        $sql2="update symptom set pname='".$pname."',number='".$number."',date='".$date."',achepath='".$achepath."',acheleft='".$acheleft."',achetop='".$achetop."', achepath1='".$achepath1."',acheleft1='".$acheleft1."',achetop1='".$achetop1."', achepath2='".$achepath2."',acheleft2='".$acheleft2."',achetop2='".$achetop2."', achepath3='".$achepath3."',acheleft3='".$acheleft3."',achetop3='".$achetop3."', achepath4='".$achepath4."',acheleft4='".$acheleft4."',achetop4='".$achetop4."', achepath5='".$achepath5."',acheleft5='".$acheleft5."',achetop5='".$achetop5."', achepath6='".$achepath6."',acheleft6='".$acheleft6."',achetop6='".$achetop6."', achepath7='".$achepath7."',acheleft7='".$acheleft7."',achetop7='".$achetop7."', achepath8='".$achepath8."',acheleft8='".$acheleft8."',achetop8='".$achetop8."', achepath9='".$achepath9."',acheleft9='".$acheleft9."',achetop9='".$achetop9."',numbpath='".$numbpath."',numbleft='".$numbleft."',numbtop='".$numbtop."', numbpath1='".$numbpath1."',numbleft1='".$numbleft1."',numbtop1='".$numbtop1."', numbpath2='".$numbpath2."',numbleft2='".$numbleft2."',numbtop2='".$numbtop2."', numbpath3='".$numbpath3."',numbleft3='".$numbleft3."',numbtop3='".$numbtop3."', numbpath4='".$numbpath4."',numbleft4='".$numbleft4."',numbtop4='".$numbtop4."', numbpath5='".$numbpath5."',numbleft5='".$numbleft5."',numbtop5='".$numbtop5."', numbpath6='".$numbpath6."',numbleft6='".$numbleft6."',numbtop6='".$numbtop6."', numbpath7='".$numbpath7."',numbleft7='".$numbleft7."',numbtop7='".$numbtop7."', numbpath8='".$numbpath8."',numbleft8='".$numbleft8."',numbtop8='".$numbtop8."', numbpath9='".$numbpath9."',numbleft9='".$numbleft9."',numbtop9='".$numbtop9."',pinpath='".$pinpath."',pinleft='".$pinleft."',pintop='".$pintop."', pinpath1='".$pinpath1."',pinleft1='".$pinleft1."',pintop1='".$pintop1."', pinpath2='".$pinpath2."',pinleft2='".$pinleft2."',pintop2='".$pintop2."', pinpath3='".$pinpath3."',pinleft3='".$pinleft3."',pintop3='".$pintop3."', pinpath4='".$pinpath4."',pinleft4='".$pinleft4."',pintop4='".$pintop4."', pinpath5='".$pinpath5."',pinleft5='".$pinleft5."',pintop5='".$pintop5."', pinpath6='".$pinpath6."',pinleft6='".$pinleft6."',pintop6='".$pintop6."', pinpath7='".$pinpath7."',pinleft7='".$pinleft7."',pintop7='".$pintop7."', pinpath8='".$pinpath8."',pinleft8='".$pinleft8."',pintop8='".$pintop8."', pinpath9='".$pinpath9."',pinleft9='".$pinleft9."',pintop9='".$pintop9."',burnpath='".$burnpath."',burnleft='".$burnleft."',burntop='".$burntop."', burnpath1='".$burnpath1."',burnleft1='".$burnleft1."',burntop1='".$burntop1."', burnpath2='".$burnpath2."',burnleft2='".$burnleft2."',burntop2='".$burntop2."', burnpath3='".$burnpath3."',burnleft3='".$burnleft3."',burntop3='".$burntop3."', burnpath4='".$burnpath4."',burnleft4='".$burnleft4."',burntop4='".$burntop4."', burnpath5='".$burnpath5."',burnleft5='".$burnleft5."',burntop5='".$burntop5."', burnpath6='".$burnpath6."',burnleft6='".$burnleft6."',burntop6='".$burntop6."', burnpath7='".$burnpath7."',burnleft7='".$burnleft7."',burntop7='".$burntop7."', burnpath8='".$burnpath8."',burnleft8='".$burnleft8."',burntop8='".$burntop8."', burnpath9='".$burnpath9."',burnleft9='".$burnleft9."',burntop9='".$burntop9."',stabpath='".$stabpath."',stableft='".$stableft."',stabtop='".$stabtop."', stabpath1='".$stabpath1."',stableft1='".$stableft1."',stabtop1='".$stabtop1."', stabpath2='".$stabpath2."',stableft2='".$stableft2."',stabtop2='".$stabtop2."', stabpath3='".$stabpath3."',stableft3='".$stableft3."',stabtop3='".$stabtop3."', stabpath4='".$stabpath4."',stableft4='".$stableft4."',stabtop4='".$stabtop4."', stabpath5='".$stabpath5."',stableft5='".$stableft5."',stabtop5='".$stabtop5."', stabpath6='".$stabpath6."',stableft6='".$stableft6."',stabtop6='".$stabtop6."', stabpath7='".$stabpath7."',stableft7='".$stableft7."',stabtop7='".$stabtop7."', stabpath8='".$stabpath8."',stableft8='".$stableft8."',stabtop8='".$stabtop8."', stabpath9='".$stabpath9."',stableft9='".$stableft9."',stabtop9='".$stabtop9."' WHERE username='".$user_name."'";

        if(mysql_query($sql2))
        {

            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "Yes", "message" : "1" } }';

        }
        else
        {
            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "No", "message" : "'.$error.'" } }';
        }

        echo $json;


        break;
    }
    case 'symptominsert':
    {
        $user_name=$_POST['username'];
        $pname=$_POST['pname'];
        $number=$_POST['number'];
        $date=$_POST['date'];
        $achepath=$_POST['achepath'];
        $acheleft=$_POST['acheleft'];
        $achetop=$_POST['achetop'];
        $achepath1=$_POST['achepath1'];
        $acheleft1=$_POST['acheleft1'];
        $achetop1=$_POST['achetop1'];
        $achepath2=$_POST['achepath2'];
        $acheleft2=$_POST['acheleft2'];
        $achetop2=$_POST['achetop2'];
        $achepath3=$_POST['achepath3'];
        $acheleft3=$_POST['acheleft3'];
        $achetop3=$_POST['achetop3'];
        $achepath4=$_POST['achepath4'];
        $acheleft4=$_POST['acheleft4'];
        $achetop4=$_POST['achetop4'];
        $achepath5=$_POST['achepath5'];
        $acheleft5=$_POST['acheleft5'];
        $achetop5=$_POST['achetop5'];
        $achepath6=$_POST['achepath6'];
        $acheleft6=$_POST['acheleft6'];
        $achetop6=$_POST['achetop6'];
        $achepath7=$_POST['achepath7'];
        $acheleft7=$_POST['acheleft7'];
        $achetop7=$_POST['achetop7'];
        $achepath8=$_POST['achepath8'];
        $acheleft8=$_POST['acheleft8'];
        $achetop8=$_POST['achetop8'];
        $achepath9=$_POST['achepath9'];
        $acheleft9=$_POST['acheleft9'];
        $achetop9=$_POST['achetop9'];
        $numbpath=$_POST['numbpath'];
        $numbleft=$_POST['numbleft'];
        $numbtop=$_POST['numbtop'];
        $numbpath1=$_POST['numbpath1'];
        $numbleft1=$_POST['numbleft1'];
        $numbtop1=$_POST['numbtop1'];
        $numbpath2=$_POST['numbpath2'];
        $numbleft2=$_POST['numbleft2'];
        $numbtop2=$_POST['numbtop2'];
        $numbpath3=$_POST['numbpath3'];
        $numbleft3=$_POST['numbleft3'];
        $numbtop3=$_POST['numbtop3'];
        $numbpath4=$_POST['numbpath4'];
        $numbleft4=$_POST['numbleft4'];
        $numbtop4=$_POST['numbtop4'];
        $numbpath5=$_POST['numbpath5'];
        $numbleft5=$_POST['numbleft5'];
        $numbtop5=$_POST['numbtop5'];
        $numbpath6=$_POST['numbpath6'];
        $numbleft6=$_POST['numbleft6'];
        $numbtop6=$_POST['numbtop6'];
        $numbpath7=$_POST['numbpath7'];
        $numbleft7=$_POST['numbleft7'];
        $numbtop7=$_POST['numbtop7'];
        $numbpath8=$_POST['numbpath8'];
        $numbleft8=$_POST['numbleft8'];
        $numbtop8=$_POST['numbtop8'];
        $numbpath9=$_POST['numbpath9'];
        $numbleft9=$_POST['numbleft9'];
        $numbtop9=$_POST['numbtop9'];
        $pinpath=$_POST['pinpath'];
        $pinleft=$_POST['pinleft'];
        $pintop=$_POST['pintop'];
        $pinpath1=$_POST['pinpath1'];
        $pinleft1=$_POST['pinleft1'];
        $pintop1=$_POST['pintop1'];
        $pinpath2=$_POST['pinpath2'];
        $pinleft2=$_POST['pinleft2'];
        $pintop2=$_POST['pintop2'];
        $pinpath3=$_POST['pinpath3'];
        $pinleft3=$_POST['pinleft3'];
        $pintop3=$_POST['pintop3'];
        $pinpath4=$_POST['pinpath4'];
        $pinleft4=$_POST['pinleft4'];
        $pintop4=$_POST['pintop4'];
        $pinpath5=$_POST['pinpath5'];
        $pinleft5=$_POST['pinleft5'];
        $pintop5=$_POST['pintop5'];
        $pinpath6=$_POST['pinpath6'];
        $pinleft6=$_POST['pinleft6'];
        $pintop6=$_POST['pintop6'];
        $pinpath7=$_POST['pinpath7'];
        $pinleft7=$_POST['pinleft7'];
        $pintop7=$_POST['pintop7'];
        $pinpath8=$_POST['pinpath8'];
        $pinleft8=$_POST['pinleft8'];
        $pintop8=$_POST['pintop8'];
        $pinpath9=$_POST['pinpath9'];
        $pinleft9=$_POST['pinleft9'];
        $pintop9=$_POST['pintop9'];
        $burnpath=$_POST['burnpath'];
        $burnleft=$_POST['burnleft'];
        $burntop=$_POST['burntop'];
        $burnpath1=$_POST['burnpath1'];
        $burnleft1=$_POST['burnleft1'];
        $burntop1=$_POST['burntop1'];
        $burnpath2=$_POST['burnpath2'];
        $burnleft2=$_POST['burnleft2'];
        $burntop2=$_POST['burntop2'];
        $burnpath3=$_POST['burnpath3'];
        $burnleft3=$_POST['burnleft3'];
        $burntop3=$_POST['burntop3'];
        $burnpath4=$_POST['burnpath4'];
        $burnleft4=$_POST['burnleft4'];
        $burntop4=$_POST['burntop4'];
        $burnpath5=$_POST['burnpath5'];
        $burnleft5=$_POST['burnleft5'];
        $burntop5=$_POST['burntop5'];
        $burnpath6=$_POST['burnpath6'];
        $burnleft6=$_POST['burnleft6'];
        $burntop6=$_POST['burntop6'];
        $burnpath7=$_POST['burnpath7'];
        $burnleft7=$_POST['burnleft7'];
        $burntop7=$_POST['burntop7'];
        $burnpath8=$_POST['burnpath8'];
        $burnleft8=$_POST['burnleft8'];
        $burntop8=$_POST['burntop8'];
        $burnpath9=$_POST['burnpath9'];
        $burnleft9=$_POST['burnleft9'];
        $burntop9=$_POST['burntop9'];
        $stabpath=$_POST['stabpath'];
        $stableft=$_POST['stableft'];
        $stabtop=$_POST['stabtop'];
        $stabpath1=$_POST['stabpath1'];
        $stableft1=$_POST['stableft1'];
        $stabtop1=$_POST['stabtop1'];
        $stabpath2=$_POST['stabpath2'];
        $stableft2=$_POST['stableft2'];
        $stabtop2=$_POST['stabtop2'];
        $stabpath3=$_POST['stabpath3'];
        $stableft3=$_POST['stableft3'];
        $stabtop3=$_POST['stabtop3'];
        $stabpath4=$_POST['stabpath4'];
        $stableft4=$_POST['stableft4'];
        $stabtop4=$_POST['stabtop4'];
        $stabpath5=$_POST['stabpath5'];
        $stableft5=$_POST['stableft5'];
        $stabtop5=$_POST['stabtop5'];
        $stabpath6=$_POST['stabpath6'];
        $stableft6=$_POST['stableft6'];
        $stabtop6=$_POST['stabtop6'];
        $stabpath7=$_POST['stabpath7'];
        $stableft7=$_POST['stableft7'];
        $stabtop7=$_POST['stabtop7'];
        $stabpath8=$_POST['stabpath8'];
        $stableft8=$_POST['stableft8'];
        $stabtop8=$_POST['stabtop8'];
        $stabpath9=$_POST['stabpath9'];
        $stableft9=$_POST['stableft9'];
        $stabtop9=$_POST['stabtop9'];

/*$user_name="silvi";
$pname="silviya";
$number="54";
$date="12/03/2014";
$achepath="resources/images/aches.png";
$acheleft="15";
$achetop="15";
$achepath1="resources/images/aches.png";
$acheleft1="25";
$achetop1="25";
$achepath2="resources/images/aches.png";
$acheleft2="35";
$achetop2="35";
$achepath3="resources/images/aches.png";
$acheleft3="45";
$achetop3="45";
$achepath4="resources/images/aches.png";
$acheleft4="50";
$achetop4="50";
$achepath5="resources/images/aches.png";
$acheleft5="60";
$achetop5="60";
$achepath6="resources/images/aches.png";
$acheleft6="70";
$achetop6="70";
$achepath7="resources/images/aches.png";
$acheleft7="80";
$achetop7="80";
$achepath8="resources/images/aches.png";
$acheleft8="90";
$achetop8="90";
$achepath9="resources/images/aches.png";
$acheleft9="100";
$achetop9="100";
$numbpath="resources/images/numb.png";
$numbleft="15";
$numbtop="15";
$numbpath1="resources/images/numb.png";
$numbleft1="25";
$numbtop1="25";
$numbpath2="resources/images/numb.png";
$numbleft2="35";
$numbtop2="35";
$numbpath3="resources/images/numb.png";
$numbleft3="45";
$numbtop3="45";
$numbpath4="resources/images/numb.png";
$numbleft4="50";
$numbtop4="50";
$numbpath5="resources/images/numb.png";
$numbleft5="60";
$numbtop5="60";
$numbpath6="resources/images/numb.png";
$numbleft6="70";
$numbtop6="70";
$numbpath7="resources/images/numb.png";
$numbleft7="80";
$numbtop7="80";
$numbpath8="resources/images/numb.png";
$numbleft8="90";
$numbtop8="90";
$numbpath9="resources/images/numb.png";
$numbleft9="100";
$numbtop9="100";
$pinpath="resources/images/pin.png";
$pinleft="15";
$pintop="15";
$pinpath1="resources/images/ pin.png";
$pinleft1="25";
$pintop1="25";
$pinpath2="resources/images/ pin.png";
$pinleft2="35";
$pintop2="35";
$pinpath3="resources/images/ pin.png";
$pinleft3="45";
$pintop3="45";
$pinpath4="resources/images/ pin.png";
$pinleft4="55";
$pintop4="55";
$pinpath5="resources/images/ pin.png";
$pinleft5="65";
$pintop5="65";
$pinpath6="resources/images/ pin.png";
$pinleft6="75";
$pintop6="75";
$pinpath7="resources/images/ pin.png";
$pinleft7="85";
$pintop7="85";
$pinpath8="resources/images/ pin.png";
$pinleft8="95";
$pintop8="95";
$pinpath9="resources/images/ pin.png";
$pinleft9="105";
$pintop9="105";
$burnpath="resources/images/ burn.png";
$burnleft="25";
$burntop="22";
$burnpath1="resources/images/ burn.png";
$burnleft1="35";
$burntop1="32";
$burnpath2="resources/images/ burn.png";
$burnleft2="15";
$burntop2="12";
$burnpath3="resources/images/ burn.png";
$burnleft3="45";
$burntop3="42";
$burnpath4="resources/images/ burn.png";
$burnleft4="50";
$burntop4="52";
$burnpath5="resources/images/ burn.png";
$burnleft5="60";
$burntop5="62";
$burnpath6="resources/images/ burn.png";
$burnleft6="70";
$burntop6="72";
$burnpath7="resources/images/ burn.png";
$burnleft7="80";
$burntop7="82";
$burnpath8="resources/images/ burn.png";
$burnleft8="90";
$burntop8="92";
$burnpath9="resources/images/ burn.png";
$burnleft9="100";
$burntop9="102";
$stabpath="resources/images/stabbing.png";
$stableft="11";
$stabtop="22";
$stabpath1="resources/images/stabbing.png";
$stableft1="22";
$stabtop1="33";
$stabpath2="resources/images/stabbing.png";
$stableft2="33";
$stabtop2="44";
$stabpath3="resources/images/stabbing.png";
$stableft3="44";
$stabtop3="55";
$stabpath4="resources/images/stabbing.png";
$stableft4="55";
$stabtop4="66";
$stabpath5="resources/images/stabbing.png";
$stableft5="66";
$stabtop5="77";
$stabpath6="resources/images/stabbing.png";
$stableft6="77";
$stabtop6="88";
$stabpath7="resources/images/stabbing.png";
$stableft7="88";
$stabtop7="99";
$stabpath8="resources/images/stabbing.png";
$stableft8="99";
$stabtop8="111";
$stabpath9="resources/images/stabbing.png";
$stableft9="111";
$stabtop9="112";

*/
        $sql3="INSERT INTO symptom(symptomno,username,pname,number,date,achepath,acheleft,achetop,achepath1,acheleft1,achetop1,achepath2,acheleft2,achetop2,achepath3,acheleft3,achetop3,achepath4,acheleft4,achetop4,achepath5,acheleft5,achetop5,achepath6,acheleft6,achetop6,achepath7,acheleft7,achetop7,achepath8,acheleft8,achetop8,achepath9,acheleft9,achetop9,numbpath,numbleft,numbtop,numbpath1,numbleft1,numbtop1,numbpath2,numbleft2,numbtop2,numbpath3,numbleft3,numbtop3,numbpath4,numbleft4,numbtop4,numbpath5,numbleft5,numbtop5,numbpath6,numbleft6,numbtop6,numbpath7,numbleft7,numbtop7,numbpath8,numbleft8,numbtop8,numbpath9,numbleft9,numbtop9,pinpath,pinleft,pintop,pinpath1,pinleft1,pintop1,pinpath2,pinleft2,pintop2,pinpath3,pinleft3,pintop3,pinpath4,pinleft4,pintop4,pinpath5,pinleft5,pintop5,pinpath6,pinleft6,pintop6,pinpath7,pinleft7,pintop7,pinpath8,pinleft8,pintop8,pinpath9,pinleft9,pintop9,burnpath,burnleft,burntop,burnpath1,burnleft1,burntop1,burnpath2,burnleft2,burntop2,burnpath3,burnleft3,burntop3,burnpath4,burnleft4,burntop4,burnpath5,burnleft5,burntop5,burnpath6,burnleft6,burntop6,burnpath7,burnleft7,burntop7,burnpath8,burnleft8,burntop8,burnpath9,burnleft9,burntop9,stabpath,stableft,stabtop,stabpath1,stableft1,stabtop1,stabpath2,stableft2,stabtop2,stabpath3,stableft3,stabtop3,stabpath4,stableft4,stabtop4,stabpath5,stableft5,stabtop5,stabpath6,stableft6,stabtop6,stabpath7,stableft7,stabtop7,stabpath8,stableft8,stabtop8,stabpath9,stableft9,stabtop9) VALUES ('','".$user_name."','".$pname."','".$number."','".$date."','".$achepath."','".$acheleft."','".$achetop."' ,'".$achepath1."','".$acheleft1."','".$achetop1."' ,'".$achepath2."','".$acheleft2."','".$achetop2."' ,'".$achepath3."','".$acheleft3."','".$achetop3."' ,'".$achepath4."','".$acheleft4."','".$achetop4."' ,'".$achepath5."','".$acheleft5."','".$achetop5."' ,'".$achepath6."','".$acheleft6."','".$achetop6."' ,'".$achepath7."','".$acheleft7."','".$achetop7."' ,'".$achepath8."','".$acheleft8."','".$achetop8."' ,'".$achepath9."','".$acheleft9."','".$achetop9."','".$numbpath."','".$numbleft."','".$numbtop."' ,'".$numbpath1."','".$numbleft1."','".$numbtop1."' ,'".$numbpath2."','".$numbleft2."','".$numbtop2."' ,'".$numbpath3."','".$numbleft3."','".$numbtop3."' ,'".$numbpath4."','".$numbleft4."','".$numbtop4."' ,'".$numbpath5."','".$numbleft5."','".$numbtop5."' ,'".$numbpath6."','".$numbleft6."','".$numbtop6."' ,'".$numbpath7."','".$numbleft7."','".$numbtop7."' ,'".$numbpath8."','".$numbleft8."','".$numbtop8."' ,'".$numbpath9."','".$numbleft9."','".$numbtop9."','".$pinpath."','".$pinleft."','".$pintop."' ,'".$pinpath1."','".$pinleft1."','".$pintop1."' ,'".$pinpath2."','".$pinleft2."','".$pintop2."' ,'".$pinpath3."','".$pinleft3."','".$pintop3."' ,'".$pinpath4."','".$pinleft4."','".$pintop4."' ,'".$pinpath5."','".$pinleft5."','".$pintop5."' ,'".$pinpath6."','".$pinleft6."','".$pintop6."' ,'".$pinpath7."','".$pinleft7."','".$pintop7."' ,'".$pinpath8."','".$pinleft8."','".$pintop8."' ,'".$pinpath9."','".$pinleft9."','".$pintop9."','".$burnpath."','".$burnleft."','".$burntop."' ,'".$burnpath1."','".$burnleft1."','".$burntop1."' ,'".$burnpath2."','".$burnleft2."','".$burntop2."' ,'".$burnpath3."','".$burnleft3."','".$burntop3."' ,'".$burnpath4."','".$burnleft4."','".$burntop4."' ,'".$burnpath5."','".$burnleft5."','".$burntop5."' ,'".$burnpath6."','".$burnleft6."','".$burntop6."' ,'".$burnpath7."','".$burnleft7."','".$burntop7."' ,'".$burnpath8."','".$burnleft8."','".$burntop8."' ,'".$burnpath9."','".$burnleft9."','".$burntop9."','".$stabpath."','".$stableft."','".$stabtop."' ,'".$stabpath1."','".$stableft1."','".$stabtop1."' ,'".$stabpath2."','".$stableft2."','".$stabtop2."' ,'".$stabpath3."','".$stableft3."','".$stabtop3."' ,'".$stabpath4."','".$stableft4."','".$stabtop4."' ,'".$stabpath5."','".$stableft5."','".$stabtop5."' ,'".$stabpath6."','".$stableft6."','".$stabtop6."' ,'".$stabpath7."','".$stableft7."','".$stabtop7."' ,'".$stabpath8."','".$stableft8."','".$stabtop8."' ,'".$stabpath9."','".$stableft9."','".$stabtop9."')";

        if(mysql_query($sql3))
        {

            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "Yes", "message" : "1" } }';

        }
        else
        {
            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "No", "message" : "'.$error.'" } }';
        }

        echo $json;

        break;
    }
    case 'symptomdelete':
    {
        $user_name=$_POST['username'];
//        $user_name="silvi";
        $sql4 ="delete from symptom where username='".$user_name."'";
        if(mysql_query($sql4))
        {

            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "Yes", "message" : "1" } }';

        }
        else
        {
            $json	= '{ "serviceresponse" : { "servicename" : "symptom Data", "success" : "No", "message" : "'.$error.'" } }';
        }

        echo $json;

        break;
    }
}
?>